### ISSUE TITLE
Allow translation using an online service

### ISSUE THREAD

**Issue by J5lx** [DaveMDS/epymc#1]
I think it would be a good idea to make it possible to translate epymc using an online service, because such are usually a lot easier to use for translators than Python scripts and GitHub. Many Open Source projects use [Transifex](https://www.transifex.com/) for this purpose:

- [XBMC](https://www.transifex.com/organization/teamxbmc) (You should definitely know this)
- [0 A.D.](https://www.transifex.com/projects/p/0ad/), a very popular Open Source RTS game
- [pacman](https://www.transifex.com/projects/p/archlinux-pacman/), the package manager of Arch Linux
- [ownCloud](https://www.transifex.com/projects/p/owncloud/), a popular cloud software
- [Tor](https://www.transifex.com/projects/p/torproject/), a anonymization network
- …and many more

It is totally free for Open Source projects and of cause it supports gettext, so why don’t start using it right now?

**Comment by DaveMDS** [comment]
So, at the end I really don't like transiflex, and noone is using it anymore
I will drop the support for transiflex
