### ISSUE TITLE
lock keyboard ability

### ISSUE THREAD

**Issue by vtolstov** [DaveMDS/epymc#10]
Thanks for good application. I have one problem - my kids love to see some videos from my notebook and some of them loves to grab keyboard and touch some buttons =))
Does it possible to write module to lock keyboard input after some locking combo?

**Comment by DaveMDS** [comment]
hehe, this is the strangest feature request I ever received :)
There are various ways to implement it, the simple one is probably to patch the keyboard module like this:

```
diff --git a/epymc/plugins/input_keyb/keyb.py b/epymc/plugins/input_keyb/keyb.py
index 5290fb1..9996dd1 100644
--- a/epymc/plugins/input_keyb/keyb.py
+++ b/epymc/plugins/input_keyb/keyb.py
@@ -84,6 +84,7 @@ class KeyboardModule(EmcModule):
       DBG('Init module')
 
       self.grab_key_func = None
+      self.blocked = False
 
       # set up default bindings
       section = 'keyboard'
@@ -114,6 +115,12 @@ class KeyboardModule(EmcModule):
       key = event.key.lower()
       DBG('Key: %s (%s)' % (key, event.key))
 
+      if key == 'f12' and event.modifier_is_set("Shift"):
+         self.blocked = not self.blocked
+
+      if self.blocked:
+         return True
+
       # if grabbed request call the grab function, else emit the signal
       if self.grab_key_func and callable(self.grab_key_func):
          self.grab_key_func(key)

```

If you apply this patch you can block/unblock the keyboard using Shift+F12
Let me know if this solution can work for you
