### ISSUE TITLE
Cannot start epymc with the last python-efl

### ISSUE THREAD

**Issue by llde** [DaveMDS/epymc#11]
Log from console
Readed config from files:

MEDIAPLAYER: Using theme: /usr/lib/python3.5/site-packages/epymc/themes/default.edj
Traceback (most recent call last):
  File "/usr/bin/epymc", line 7, in <module>
    sys.exit(start_epymc())
  File "/usr/lib/python3.5/site-packages/epymc/main.py", line 97, in start_epymc
    if not gui.init():
  File "/usr/lib/python3.5/site-packages/epymc/gui.py", line 109, in init
    preferred_engine_set(evas_engine)
  File "efl/utils/deprecated.pyx", line 84, in efl.utils.deprecated.WRAPPER.__call__ (efl/utils/deprecated.c:2193)
TypeError: Expected tuple, got FrameSummary

**Comment by llde** [comment]
It work commenting preferred_engine_set(evas_engine)

**Comment by DaveMDS** [comment]
Thanks for reporting!
This is an error in python-efl not in epymc, epymc is just using a deprecated function and python-efl is failing in reporting the deprecation. We investigate a bit and found that python3.5 change the traceback API :(

In the meantime I can simply fix epymc to not use the deprecated function anymore, will do this tomorrow.

**Comment by kaihu** [comment]
Incompatibility with Python 3.5 has now been fixed in python-efl with commit 8f2baa86b5695d4daf5de086b142a37363337a87

**Comment by llde** [comment]
It should be possbile to have a bugfixing release?
Thanks to both.

**Comment by DaveMDS** [comment]
Sorry, a bug fix release will take me too much time, and that resource is really low atm.
Btw the next stable release will come in less than 30 days
