### ISSUE TITLE
Can not build epymc 1.1.0

### ISSUE THREAD

**Issue by ak137** [DaveMDS/epymc#13]
pi@raspberrypi:~/Desktop/epymc-1.1.0 $ python setup.py build
running build
running build_themes
building theme: "default" from: data/themes/default/default.edc
error: [Errno 2] No such file or directory

**Comment by DaveMDS** [comment]
so strange, the file default.edc is there in the distribution tgz
Can you see the file in the path given on the error line?
maybe a download or untar problem?
do you get the same error doing "python setup.py install" ?

**Comment by wfx** [comment]
Close?
