### ISSUE TITLE
Desktop file is missing a semi colon

### ISSUE THREAD

**Issue by simotek** [DaveMDS/epymc#15]
One line is missing a trailing semicolon which is being picked up by openSUSE's .desktop file validation tools.

--- epymc-1.2.0/data/desktop/epymc.desktop
+++ epymc-1.2.0/data/desktop/epymc.desktop

-Actions=Movies;TvShows;OnlineChannels;Music;Mame;Photo
+Actions=Movies;TvShows;OnlineChannels;Music;Mame;Photo;
 
 [Desktop Action Movies]
 Exec=epymc --activity movies

**Comment by DaveMDS** [comment]
Thanks!
