### ISSUE TITLE
Correct epymc_xsession.desktop Icon

### ISSUE THREAD

**Issue by wltjr** [DaveMDS/epymc#19]
Presently in the epymc_xsession.desktop the icon is set to the name, which fails on lookup in most situations. A fix is to specify the absolute path to the file.

Change
```
Icon=epymc
```
To
```
Icon=/usr/share/icons/hicolor/64x64/apps/epymc.png
```
I can submit a PR but seemed like a pretty minor thing for a PR.

**Comment by DaveMDS** [comment]
hmmm, hard-coding the path doesn't seems the correct solution to me, icons can be installed in different paths based on system configuration (that is "/usr/share" can be different).

It seems to me more a missing feature (bug?) in your login manager, what are you using to login?

Otherwise I need to edit the .desktop file on build/install (like usually happen with autofoo stuff) but this is not really a clean solution to my eyes.

**Comment by wltjr** [comment]
I am using entrance, and the [E session](https://git.enlightenment.org/core/enlightenment.git/tree/data/xsession/enlightenment.desktop.in) entry has this path hard coded via autotools. Login managers may not have an icon pack selected. I am not sure using just the name is the correct way. Very few if any log in mangers seem to use such icons. Others like plasma do not have an icon at all. I can see about changing the code in entrance to find the image. Not sure that is correct given how E hard codes a path to the icon file in its xsession desktop entry.

**Comment by DaveMDS** [comment]
FDO spec says:

> Icon to display in file manager, menus, etc. If the name is an absolute path, the given file will be used. If the name is not an absolute path, the algorithm described in the Icon Theme Specification will be used to locate the icon. 

source: https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

So the way epymc set the icon is correct and entrance should search the icon using the theme spec (if icon is not a full path of course)

If you use efreet in entrance than it should be a really easy to correctly follow the standard :)

**Comment by wltjr** [comment]
Then tell my why Enlightenment does it differently? I assume they did that for a reason. They could do it just as you do, but they did not. Why?

You are actually reading that spec incorrectly

"Icon to display in file manager, menus, etc. If the name is an absolute path, the given file will be used. If the name is not an absolute path, the algorithm described in the Icon Theme Specification will be used to locate the icon."

Thus the order is
1. If its an absolute path use that
2. If it is NOT an absolute path then use the Theme Specification.

Absolute path comes before looking up an icon by name. That is a Desktop Entry specification and this usage is in Display Manager, pre-desktop. I do not believe the same rules apply and you cannot make the same assumptions. Only Lightdm uses system themes. SDDM and Entrance, likely others like anna, all use their own theme that has nothing to do with a desktop theme. Thus cannot rely on Desktop Entry spec, or that a theme will be set to be able to lookup items.

I was going to modify Entrance code, but then I have to code a special case for epymc only. That does not make much sense. I looked at the Enlightenment desktop entry for its xession, and it uses a absolute path. Enlightenment is likely doing it for a reason. Thus epymc should likely do the same.

**Comment by wltjr** [comment]
It is up to you either way, I already addressed this in the [epymc ebuild]() I made. I modify via sed. Just wanted to be consistent with other E stuff, and wasn't sure if I should modify entrance code or not. I can always use eina_file_path_relative and switch between elm_image_file_set and elm_image_icon_get. Or drop the icon aspect entirely. But if epymc is the only thing doing it that way, seems a bit much to code for a corner case.

As a closing note, I think use of desktop files for xsessions is likely abuse of that specification. Though it is the current standard way. Just mentioning that for the irony. I think they will be used for Wayland sessions as well but maybe not. Anyway up to you from here. Thank you for your time and consideration.

**Comment by DaveMDS** [comment]
I'm not reading the spec incorrectly! the spec is REALLY clear: you can use a full path OR just the name,
there is no priority involved...Both method are valid, any other interpretation is just speculations :)

I really think using only the name is much better, as in this way the DM can choose to show a different icon for styling purpose. (infact I was doing this in a  lightdm efl greater theme)

In the end I really suggest you to fix Entrance...at least if you want it to be FDO compliant.

**Comment by wltjr** [comment]
I will ask Carsten a some point [he is the one who added the icon](https://git.enlightenment.org/core/enlightenment.git/commit/data/xsession/enlightenment.desktop.in?id=df56bb3761950053c708db6fa7e9287f6541246f) to E's xsession desktop entry file.

That the spec starts with full path, then goes to name, shows its secondary. Otherwise it would say it starts with FDO and then tries absolute. The reason is because the FDO logic uses more resources than via absolute path. [Icon lookup logic](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup)

Also your assuming 2 things here.
 - That someone else will make a different Epymc icon. Which does not exists now. If no other exist, then via name or path is moot as there is no alternative for FDO to use/find if they switch icon sets.
 - That someone will want to override a X session icon, if another icon is even available

FDO is about desktop icons in menus, buttons, toolbars, etc. This is about X sessions, that would be identified via Logo/brand, E logo for E, gnome Foot, kde K, etc. Thus the user can visually select which session based on icon. Those are not likely to change, and rarely does a icon set override a brand logo like that.

I will change entrance IF and WHEN the E xsession desktop entry switches from absolute to name. Or if I come across another that does it that way. Presently only E and Epymc are setting icons at all. One does it via absolute, one via name. I have to go with Carsten did it that way for a  reason. More will log into E desktop than Epymc. Thus if one is correct and one is wrong, seems Epymc is wrong and E is correct. E is used by considerably more.

I still have to see what it will take to log into Epymc, as it does not work. Which is another matter entirely. Thus the icon is completely moot if you cannot log in or use it. But again unless another alternative icon is exists with the same name. Using a name lookup gives you nothing. It will always be that 1 icon till another exists.

Anyway no need for further discussion.

**Comment by DaveMDS** [comment]
I agree with you: no need for further discussion  :P
