### ISSUE TITLE
Accelerate the music scan

### ISSUE THREAD

**Issue by J5lx** [DaveMDS/epymc#2]
Currently the music scan is *way* to slow. epymc needs about 6.5 minutes to scan my library which currently consists of ~3800 Tracks, that’s about 10 tracks per second. To show you how slow that actually is, here’s a comparison between epymc and a few other audio managers I tried out over time:

Program | Time needed for full scan | Tracks per second
---------|------------------------------------|--------------------------
epymc | ~6.5 minutes | ~10
Rhythmbox | ~2.5 minutes | ~25
Audacious | ~2 minutes | ~30
Nightingale | ~1.5 minutes | ~40
Enjoy | ~55 seconds | ~70
DeaDBeeF | ~40 seconds | ~95
Quod Libet | ~20 seconds | ~190

As you can see epymc has by far the slowest scanner I ever experienced. Please change that! It would be great if it could be at least faster than Rhythmbox’s.

Maybe you want to look at the code of [Quod Libet](http://code.google.com/p/quodlibet/) since handling a lot of files whithout getting slow is one of it’s official features.

And, btw, in general I really like epymc. Of course it’s not on par with the big players like XBMC, but hey, it’s also not even 1.0 while XBMC is already version 13! Please keep up the good work.

**Comment by kaihu** [comment]
Can someone test the fix? I don't have a local collection of music files to test it with.

**Comment by J5lx** [comment]
I'll test it as soon as python-efl in the AUR gets updated to 1.18. It's already flagged out-of-date.

**Comment by llde** [comment]
I will update tonight or tomorrow on Aur

**Comment by DaveMDS** [comment]
So this are my results using current git version (with latest changes, not in the 1.2.0-beta1)

My library is 3664 songs/296 albums/122 artists. 
Note that I have the library on a network share and a fast local SSD disk, so I'm probably not affected as you

```
EpyMC:      2m:50s (cold start)   0m:15s (hot start)
Quodlibet:  2m:22s (cold start)   (not tryed hot)
```

between each test I'm doing:
```
rm ~/.config/epymc/db_py3_music_*
rm ~/.quodlibet/songs
sync
echo 3 > /proc/sys/vm/drop_caches
```

The last 2 lines are really important, they clear the kernel file cache, thus always simulating a "cold start"

**Comment by J5lx** [comment]
These are my results with a library of 4330 songs / 507 albums / 217 artists:

Player | Cold Start | Hot Start
-----------|-----------------|----------------
EpyMC | 2m:40s (27/s) | 1m:10s (61/s)
Quod Libet | 1m:30s (48/s) | 0m:10s (433/s)

EpyMC still isn't quite as good as QL, but at least it's faster than Rhythmbox now (according to the initial test I made when opening this issue). Since that was my original appeal I'll close this issue now :) Thanks for taking care of this!

**Comment by DaveMDS** [comment]
I have done more tests, with a more realistic scenario (music library and the dbs on the same slow HDD), with different sdb implementation. 3 try for each test, always "cold":

Test | result 1 | result 2 | result 3
-----|----|----|----
Std Shelve, sync at every write | 13:02 | 13:10 | 13:14
Std Shelve, delayed sync | 1:14 |  1:15 |  1:15
Std Shelve, delayed sync +writeback | 1:15 |  1:14 |  1:13
EpyMC shelve (dbm.gbu) delayed sync | 1:14 |  1:15 |  1:15
EpyMC shelve (dbm.gbu) delayed sync +writeback | 1:14 |  1:15 |  1:15
Quodlibet | 0:52 | 0:51 | 0:51

Looking at this results I'm going to implement the standard shelve + delayed sync approach
