### ISSUE TITLE
Build with python2

### ISSUE THREAD

**Issue by awissu** [DaveMDS/epymc#20]
Hi! 
I bumped on problem when building rpm in OBS:
```
[   55s] + python setup.py build
[   55s]   File "setup.py", line 222
[   55s]     "Found: %s  (need >= %d.%d.%d)" % (py_ver, *minv)
[   55s]                                                ^
[   55s] SyntaxError: invalid syntax
```

**Comment by DaveMDS** [comment]
will look into this asap

**Comment by DaveMDS** [comment]
Hi, 
commit 9c0eebcd85e74ffe0318f02867fd1106905d7736 should fix your error, but note that py2 is no more supported, you need to build epymc with python3.

please check that the error is fixed also for you and close this task accordly.

Thanks

**Comment by awissu** [comment]
Thanks.
