### ISSUE TITLE
Youtube plugin no longer functions

### ISSUE THREAD

**Issue by simotek** [DaveMDS/epymc#6]
All the groups come up with no items in them, Top rated just comes up with a device support message saying this device is no longer supported

**Comment by DaveMDS** [comment]
arghh, I was waiting for this :(
The old (anonymous) youtube api is gone into the void
I need to rewrite the channel using a different method
Thanks for the report

**Comment by DaveMDS** [comment]
Ok, this should be fixed with the latest commits.
Can you confirm it works also for you?

**Comment by simotek** [comment]
yep good now, getting a new release anytime soon?

**Comment by DaveMDS** [comment]
yes, the 1.1 release will be available soon
I hope I can find the time in the next 30 days
